# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy WAR app to Azure Web App - microbedb

on:
  push:
    branches:
      - microbedb

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '8'

    - name: Build with Maven
      run: mvn clean install

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'microbedb'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1cfb42ba9af5414085d13afa6904055c }}
        package: '${{ github.workspace }}/target/*.war'